---
- name: Installing a package
  hosts: all
  become: true
  
  tasks:
   - name: Installing a package httpd 
     yum:
      name: httpd
      state: installed
     when: ansible_os_family == "RedHat"

   - name: Start httpd service
     service:
      name: htt----
      state: started
     when: ansible_os_family == "Redhat"
     

   - name: Install apache2 package
     apt:
      name: apache2
      state: present
     when: ansible_os_family == "Debian"

   - name: start apache2 service
     service:
      name: apache2
      state: started
     when: ansible_os_family == "Debian"   

   - name: Copying index.html
     copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0777 
