---
# tasks file for setup-apache-role
#
- name: Installing a package httpd
  yum:
     name: httpd
     state: installed
  when: ansible_os_family == "RedHat"
  notify: Start httpd service


- name: Install apache2 package
  apt:
     name: apache2
     state: present
  when: ansible_os_family == "Debian"
  notify: Start apache2 service


- name: Copying index.html
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0777


